version: '3.6'

services:
  moonlifters:
    build: .
    ports:
    - 8082:8082
    env_file:
      - .env

  mysql:
    image: mysql:8.1.0
    expose:
      - 33060
    volumes:
      - ./all-tables.sql:/docker-entrypoint-initdb.d/all-tables.sql
    env_file:
      - .env
